### ISSUE TITLE
Submit gopher.el to MELPA

### ISSUE THREAD

**Issue by msnyder-info** [msnyder-info/gopher.el#14]
See melpa/melpa#6021.

**Comment by Chobbes** [comment]
@msnyder-info should we poke the melpa issue? I think all of the issues have been addressed now, except for maybe the comment about `[` and `]`, but those seem to work just fine for me.

**Comment by gum3n** [comment]
<kbd>[</kbd> and <kbd>]</kbd> works fine for me as well. Maybe issue occurs only on some gopher holes.

**Comment by wasamasa** [comment]
I think this can be closed now.

**Comment by kensanata** [comment]
Indeed. Thank you all.
