### ISSUE TITLE
goto HTML url at point

### ISSUE THREAD

**Issue by gum3n** [msnyder-info/gopher.el#19]
Hi. On my gopher hole I have a lot of html links. Currently, visiting these links is very user-unfriendly (or maybe I'm missing something?).

I have modify `gopher-goto-url-at-point` function to support html links using `browse-url` function. It will open html link in your default web browser eww, firefox etc. (browser can be changed by setting `browse-url-browser-function` variable).

It works like a charm for me so I thought to share this idea with you.

```lisp
(defun gopher-goto-url-at-point (&optional arg)
  "Navigate to the URL at point, or the URL contained in ARG, if present."
  (interactive)
  (move-beginning-of-line nil)
  (let* ((properties (text-properties-at (point)))
         (content-type (gopher-get-content-type properties)))
    (cond ((eq content-type 'html)
           (browse-url (replace-regexp-in-string "\\(/\\)*URL:" "" (cl-getf properties :selector))))
          ((eq content-type 'search-query)
           (call-interactively 'gopher-goto-search))
          (t (gopher-goto-url (cl-getf properties :hostname)
                              (cl-getf properties :port)
                              (cl-getf properties :selector)
                              content-type)))))
```

I just replaced `if` with `cond`. Then for html content type it's using `browser-url` function. I can create PR if you like.

**Comment by msnyder-info** [comment]
Hi gum3n, sorry for the slow response.

If you are willing to create a PR, then please do! I'm happy to accept simple fixes like this.

**Comment by kensanata** [comment]
Feel free to reopen if it doesn't work as expected.
