### ISSUE TITLE
Info key bindings

### ISSUE THREAD

**Issue by rnkn** [msnyder-info/gopher.el#5]
I love that you're making an Emacs interface for gopher!

One suggestion (and I know I can simply set this myself) is to use the same/similar key bindings as [Info](https://www.gnu.org/software/emacs/manual/html_mono/info.html), e.g. "L" for back, etc.

**Comment by msnyder-info** [comment]
Hi, and thank you for the feedback!

Would you be interested in providing a pull request for this?

**Comment by kensanata** [comment]
It's tricky. Info uses `l` for back in history and `r` for forward in history. But we use `r` for reload. Based on my experience with other Emacs modes I'd expect `g` to reload the buffer, but we use `g` for "go to". And by now I'm running out of ideas.

Let's look at EWW? Interesting, it also uses `l` for back in history and `r` for forward in history, `g` for reload and `G` for `eww` (i.e. "go to"). So perhaps that should be our model?

**Comment by rnkn** [comment]
Alex beat me to it.
