### ISSUE TITLE
Add TLS support

### ISSUE THREAD

**Issue by kensanata** [msnyder-info/gopher.el#8]
My gopher site at alexschroeder.ch is available on both port 70 using a plain connection, and on port 7443 using a TLS connection.

**Comment by msnyder-info** [comment]
I added some comments on your commit: 
https://github.com/msnyder-info/gopher.el/pull/9/files

I’m just pinging here because I don’t know if you get any kind of notification for code reviews. Does that work as expected?

**Comment by kensanata** [comment]
Both worked as expected, no worries. 😀

-- 
Typed on a tiny keyboard. Sorry for being terse.
